### ISSUE TITLE
Storage optimized types fail with global encryption set to true.

### ISSUE THREAD

**Issue by blyles** [cloudfoundry/bosh-aws-cpi-release#139]
In an attempt to use instance storage types we can accross the following issue, if you set a storage optimized type like so.

```
- cloud_properties:
      ephemeral_disk:
        use_instance_storage: true
      instance_type: i3.large
    name: i3.large-raw
```

And have encryption enabled at a global level, here.

https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/23e4e3ede33e1fd27369abed897f1cefa127a946/src/bosh_aws_cpi/lib/cloud/aws/cloud_props.rb#L185-L202

Seems to break the flow and prevent the instance from spinning up.  Resulting in a timeout on creation.

```
Task 4539876 | 10:52:23 | Creating missing vms: emptyvm/ed3274fb-2996-4451-830e-177faeb8db1d (0) (00:11:15)
                        L Error: Timed out pinging VM 'i-015b264123ac00e91' with agent '34321d55-2440-430d-8c48-ec74bcfd0978' after 600 seconds
```

We think its because of the validation here: 

https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/23e4e3ede33e1fd27369abed897f1cefa127a946/src/bosh_aws_cpi/lib/cloud/aws/cloud_props.rb#L198-L202

And seeing that its already enabled by default, we think its a bug, we raised this in the cloud foundry slack as well and were pointed this path.
