### ISSUE TITLE
Working with AWS china Ningxia region

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/bosh-aws-cpi-release#83]
Hi Team,  working of aws china, ningxia region (cn-nortwest-1). I have workstation and bosh deployed in  eu-west-1  and trying to deploy in china
Got following error, while uploading light-stemcell
```
Error 100: Unknown CPI error 'Unknown' with message 'undefined method `endpoint' for #<Aws::EC2::Client>' in 'create_stemcell' CPI method
```
added  cn endpoint properties in bosh via manifest:
```
properties:
  aws:
    ec2_endpoint: "<redacted>"
    elb_endpoint: "<redacted>"

```
Still facing same error,  is there anything else to be configure with  bosh to work with china region
